ready/community-broadband-kit

README.md

I went through the `README` file, it was really well written! I just fixed a small typo and added empty lines between parameters so they appear on their own line instead of in a paragraph together
N/A
N/A

`README` edits

---

static/index.css
templates/testTemplate.js

- Centered router checklist item
- Removed step 5 in progress bar

Small checklist fix

---

app.js
app.yaml

Small change to gcloud storage key config

fix: small change to gcloud storage key config

---

app.js
utils/constants.js

- Added separate config for cloud storage in local and deployed environments

Updated cloud storage config

---

app.js
routes/metadata.js
utils/constants.js
utils/metadata/metadata.js

- Refactored isp and city lookup
- Added log statements to metadata lookup

Metadata lookup refactor

---

.gitignore
app.js
routes/metadata.js
utils/constants.js
utils/metadata/metadata.js

- Updated destination paths for download database files
- Removed log statements

Metadata refactor

---

app.js
cloudbuild.yaml

- Updated cloudbuild to include database files from cloud storage

Updated cloudbuild to include database files from cloud storage

---

templates/testTemplate.js

- Added a retake test option
- Updated question 4 of the checklist 
Closes ready/multitest#98
Closes ready/multitest#99

Small changes to test

---

static/index.css
templates/endTemplate.js
templates/footerTemplate.js
templates/headerTemplate.js
utils/constants.js

- Changed logo sizing from dynamic resizing on the client size to using max/min height/width
- Fixed issues with responsiveness in the nav bar
- Move google translate button between main nav bar and hamburger menu based on window size

Improved logo sizing, added translate button to hamburger menu

---

static/history/history.js
static/measure/handleResults.js
static/utils/resultsUtils.js
templates/resultsTemplate.js
utils/resultsUtils.js

- Moved calculation of median results after running test to frontend
- Upload median results to database after running test
- Use backend endpoint only for getting service status

Fixed bugs with uploading and displaying test results

---

templates/testTemplate.js

- Added "See your state broadband audit" CTA at the end of the test 
- Points to broadband audit main page for now
Closes ready/multitest#116

Broadband audit CTA at end of test

---

templates/footerTemplate.js
templates/headerTemplate.js

- Removed BBM branding across header and footer if domain name is www.checknewarkinternetspeeds.org
- To test set config to newark test instance
Closes ready/multitest#119

Removed bbm branding for newark test instance

---

routes/emailReminder.js

- remove send remind email when clicking on remind me btn
- add fromName and fromEmail fields to notionDB

Email reminder

---

routes/addEmail.js
routes/emailReminder.js
static/utils/sendEmails.js

add url to notion db

---

templates/testTemplate.js

- Removed audit link at end of test per Avatarius' request

Removed audit link 

---

static/measure/handleResults.js
static/measure/setup.js

- Fixed bug with noService report trying to upload undefined value when going through the same-setup flow
- Removed saving address in session storage
1. Choose 'yes' to same setup question
2. Should successfully upload test data upon completion of test
Closes ready/multitest#117

Fix noService upload

---

static/map/getAggregateMultitestResultsQuery.js
static/map/map.js
templates/statisticsTemplate.js

Changed references to "unique devices" to "total addresses" to match backend changes in the resolvers

fix: updated references to unique devices to be total addresses

---

routes/emailReminder.js
utils/constants.js
utils/getAssets.js

- Remove www when checking the domain of the request
- Change from email for Newark's email reminder

Updates for Newark

---

static/measure/handleResults.js
static/measure/setup.js
static/measure/survey.js

- Fixed bug with uploading undefined values when leaving checklist questions unanswered (in the case of having no history of tests taken)

Upload results bug fix

---

app.js
static/index.css
static/measure/config.js
static/measure/handleResults.js
static/measure/setup.js
static/test/runTests.js
static/utils/resultsUtils.js
templates/footerTemplate.js
templates/headerTemplate.js
templates/indexTemplate.js
templates/testTemplate.js
utils/resultsUtils.js

- Hid history page
- Hid results page
- Skip Ookla test
- Hide public map component
- Add Uknown status tag

Temporarily hide history and results page, ookla test

---

static/measure/config.js
static/test/runTests.js
utils/constants.js

- Uncommented ookla speed test

chore: unskip ookla test

---

README.md
package-lock.json
package.json
static/measure/config.js
static/test/runTests.js
utils/constants.js

Prod deploy

---

static/measure/survey.js

Closes issue -> [MVR ticket](https://github.com/ready/ready-engineering/issues/91)
Related PR -> Boss platform [pull request](https://github.com/ready/boss-platform/pull/201)
Related PR -> RGA [pull request](https://github.com/ready/ready-gov-audit/pull/971)

feat: migrate internet speed survey api mutation
